CREATE DATABASE ADDRESSBOOK;
SHOW DATABASES;

USE ADDRESSBOOK;
CREATE TABLE ADDRESSBOOK (
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
ZIPCODE BIGINT NOT NULL,
PHONENUMBER BIGINT NOT NULL,
EMAIL VARCHAR(50)
);
DESC ADDRESSBOOK