CREATE DATABASE ADDRESSBOOK;
SHOW DATABASES;

USE ADDRESSBOOK;
CREATE TABLE ADDRESSBOOK (
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
ZIPCODE BIGINT NOT NULL,
PHONENUMBER BIGINT NOT NULL,
EMAIL VARCHAR(50)
);
DESC ADDRESSBOOK;

INSERT INTO ADDRESSBOOK VALUES ('SWEETY','BOTLA','SRINAGAR','NANDED',431901,9809898712,'ABC@GMAIL.COM'),
								('GIRI','SHINDE','VAZIRABAD','PUNE',789872,90987655162,'HNB@GMAIL.COM.IN'),
                                ('RAHUL','MEHTA','SHYAMNAGAR','NANDED',898981,8987876521,'XYZ@GMAIL.COM');
SELECT * FROM ADDRESSBOOK;

UPDATE ADDRESSBOOK SET CITY='MUMBAI' WHERE FIRSTNAME='SWEETY';
UPDATE ADDRESSBOOK SET ZIP=999999 WHERE FIRSTNAME='GIRI';
UPDATE ADDRESSBOOK SET ADDRESS='BHAGYANAGAR' WHERE FIRSTNAME='SWEETY';

DELETE FROM ADDRESSBOOK WHERE FIRSTNAME='RAHUL';

SELECT * FROM ADDRESSBOOK WHERE CITY='MUMBAI';
SELECT * FROM ADDRESSBOOK WHERE ZIP=999999;

SELECT CITY,COUNT(FIRSTNAME) FROM ADDRESSBOOK GROUP BY CITY;

SELECT FIRSTNAME,CITY FROM ADDRESSBOOK GROUP BY CITY ORDER BY FIRSTNAME ASC;

ALTER TABLE ADDRESSBOOK ADD TYPE VARCHAR(50) AFTER LASTNAME;
UPDATE ADDRESSBOOK SET TYPE='FAMILY' WHERE FIRSTNAME='SWEETY';
UPDATE ADDRESSBOOK SET TYPE='ROOMATES' WHERE FIRSTNAME='GIRI';

SELECT TYPE,COUNT(FIRSTNAME) FROM ADDRESSBOOK GROUP BY TYPE;